/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Add: (typeof import('../module/mod-flow/node/Add.vue'))['default'];
    App: (typeof import('./../App.vue'))['default'];
    Application: (typeof import('./../components/Application/Application.vue'))['default'];
    Chat: (typeof import('./../module/mod-chat/chat/index.vue'))['default'];
    ChatMessage: (typeof import('./../components/chat/message/ChatMessage.vue'))['default'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
    ElContainer: (typeof import('element-plus/es'))['ElContainer'];
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer'];
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu'];
    ElHeader: (typeof import('element-plus/es'))['ElHeader'];
    ElIcon: (typeof import('element-plus/es'))['ElIcon'];
    ElMain: (typeof import('element-plus/es'))['ElMain'];
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch'];
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
    FbHeader: (typeof import('./../components/Common/FbHeader.vue'))['default'];
    FbVersion: (typeof import('./../components/Common/FbVersion.vue'))['default'];
    Header: (typeof import('./../layout/Header/index.vue'))['default'];
    Info: (typeof import('./../module/mod-chat/info/index.vue'))['default'];
    Input: (typeof import('./../module/mod-chat/components/Input.vue'))['default'];
    Layout: (typeof import('./../layout/index.vue'))['default'];
    MarkdownRender: (typeof import('./../components/chat/message/MarkdownRender.vue'))['default'];
    ModChat: (typeof import('./../module/mod-chat/index.vue'))['default'];
    ModelInfo: (typeof import('./../module/mod-chat/components/ModelInfo.vue'))['default'];
    ModelSelectorDisplay: (typeof import('./../components/model/ModelSelectorDisplay.vue'))['default'];
    ModFeedback: (typeof import('./../module/mod-feedback/index.vue'))['default'];
    ModFlow: (typeof import('./../module/mod-flow/index.vue'))['default'];
    ModHistory: (typeof import('./../module/mod-history/index.vue'))['default'];
    ModKnowledge: (typeof import('./../module/mod-knowledge/index.vue'))['default'];
    ModLogin: (typeof import('./../module/mod-login/index.vue'))['default'];
    ModSettings: (typeof import('./../module/mod-settings/index.vue'))['default'];
    ModTool: (typeof import('./../module/mod-tool/index.vue'))['default'];
    NAvatar: (typeof import('naive-ui'))['NAvatar'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCollapse: (typeof import('naive-ui'))['NCollapse'];
    NCollapseItem: (typeof import('naive-ui'))['NCollapseItem'];
    NDataTable: (typeof import('naive-ui'))['NDataTable'];
    NDivider: (typeof import('naive-ui'))['NDivider'];
    NDrawer: (typeof import('naive-ui'))['NDrawer'];
    NDrawerContent: (typeof import('naive-ui'))['NDrawerContent'];
    NEllipsis: (typeof import('naive-ui'))['NEllipsis'];
    NFlex: (typeof import('naive-ui'))['NFlex'];
    NForm: (typeof import('naive-ui'))['NForm'];
    NFormItem: (typeof import('naive-ui'))['NFormItem'];
    NIcon: (typeof import('naive-ui'))['NIcon'];
    NIconWrapper: (typeof import('naive-ui'))['NIconWrapper'];
    NInput: (typeof import('naive-ui'))['NInput'];
    NLayout: (typeof import('naive-ui'))['NLayout'];
    NModal: (typeof import('naive-ui'))['NModal'];
    Node: (typeof import('./../module/mod-flow/node/Node.vue'))['default'];
    NPagination: (typeof import('naive-ui'))['NPagination'];
    NPopover: (typeof import('naive-ui'))['NPopover'];
    NPopselect: (typeof import('naive-ui'))['NPopselect'];
    NResult: (typeof import('naive-ui'))['NResult'];
    NSpace: (typeof import('naive-ui'))['NSpace'];
    NSwitch: (typeof import('naive-ui'))['NSwitch'];
    NTab: (typeof import('naive-ui'))['NTab'];
    NTabs: (typeof import('naive-ui'))['NTabs'];
    NTag: (typeof import('naive-ui'))['NTag'];
    NText: (typeof import('naive-ui'))['NText'];
    Panel: (typeof import('./../module/mod-flow/panel/index.vue'))['default'];
    ParentLayout: (typeof import('./../layout/parent-layout.vue'))['default'];
    Provider: (typeof import('./../components/Application/Provider.vue'))['default'];
    Quote: (typeof import('./../module/mod-chat/components/Quote.vue'))['default'];
    Recommend: (typeof import('./../module/mod-chat/components/Recommend.vue'))['default'];
    RecommendItem: (typeof import('./../components/chat/recommend/RecommendItem.vue'))['default'];
    Record: (typeof import('./../module/mod-history/components/table/Record.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SettingOption: (typeof import('./../components/Settings/SettingOption.vue'))['default'];
    SettingsPanel: (typeof import('./../module/mod-settings/components/SettingsPanel.vue'))['default'];
    StartNode: (typeof import('./../module/mod-flow/node/StartNode.vue'))['default'];
    SwitchTheme: (typeof import('./../module/mod-settings/components/SwitchTheme.vue'))['default'];
    TabGroup: (typeof import('./../layout/components/Header/TabGroup.vue'))['default'];
    Table: (typeof import('./../module/mod-history/components/table/index.vue'))['default'];
    ToolGroup: (typeof import('./../module/mod-tool/components/ToolGroup.vue'))['default'];
    ToolItem: (typeof import('./../components/Tools/ToolItem.vue'))['default'];
    TreeNode: (typeof import('./../module/mod-flow/node/TreeNode.vue'))['default'];
  }
}
